/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sugar_patch_Updater */

#ifndef _Included_com_sugar_patch_Updater
#define _Included_com_sugar_patch_Updater
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sugar_patch_Updater
 * Method:    applyPatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_sugar_patch_Updater_applyPatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
